Task1 ver1
m-kulygin/hh-school-2022-java-collections-stream pull request #1
Opened 2022-12-21 06:17 UTC by m-kulygin

2022-12-26 05:48 UTC, genroelgvozo requested changes

2022-12-26 05:48 UTC, genroelgvozo commented on src/main/java/tasks/Task3.java
> +  {
шо, сиплюсплюсник что-ли?)

скобочки открывающие оставляем на предыдущей строке)

2022-12-26 05:48 UTC, genroelgvozo commented on src/main/java/tasks/Task3.java
> +            .sorted(Comparator.comparing(Person::getSecondName)
код иногда падать будет, почему?

2022-12-26 05:48 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +            .flatMap(Set::stream)
а вот же можно убрать collect в map, а map сразу заменить на flatMap, и вообще без скобочек сделать цепочку (зачем переменная непонятно там)

2022-12-26 05:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  // ИЗМЕНЕНО: метод переписан на стримах с добавлением null-case проверок.
а чем плохо изначально было?

2022-12-26 05:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +                    Optional.ofNullable(person.getMiddleName()).orElse(""));
" Олег " - чето лишние пробелы)

ну и trim не спасет от "Негрозов__Александрович"

в целом код говорит что сделать, но делает это не очень качественно (и даже уже отлично от исходного, хоть там тоже был баг)

хотелось бы не вникать в технические детали c этими пробелами, а просто прочесть че тут происходит - посмотри на Collectors.joining()

2022-12-26 05:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +            .collect(Collectors.toMap(Person::getId, this::convertPersonToString));
твой код иногда будет падать, мой не падал

2022-12-26 05:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    } catch (Exception e) { System.err.println("EXCEPTION: " + e.getMessage()); }
непонял, а catch здесь зачем?)

там же если и кидается то рантайм, зачем ловить то? т.е. если что-то пошло не так и не смогли просто получить нормальный результат, ты возвращаешь false, который может быть ложным результатом а не кидаешь ошибку - не надо так)

2022-12-26 05:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    } catch (Exception e) { System.err.println("EXCEPTION: " + e.getMessage()); }
ну и вопрос - за сколько будет выполняться метод?

2022-12-26 05:48 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  public long countEven(Stream<Integer> numbers) // убрано ненужное внутреннее поле count; избыточная манипуляция с этим полем заменена на встроенный метод count
а чем плоха изначальная манипуляция?) я люблю манипулировать

2022-12-28 14:21 UTC, m-kulygin commented
###  **28.12.2022 Исправления ДЗ по Java**

### _Task 3_
- добавлены различные null-case проверки;
- обновлено форматирование (перенесена фигурная скобка)

_Предыдущая версия когда иногда падала, потому что отсутствовали null-case проверки, а именно:_
_- если поступающая коллекция == null_
_- если какой-либо из элементов коллекции == null - упадёт на вызовах методов типа getFirstName ..._
_- если какие-то поля у конкретной персоны == null - упадёт на сортировке, что поправляется использованием null-friendly компаратора_

### _Task 4_
- обновлено форматирование (перенесена фигурная скобка)

### _Task 5_
- обновлено форматирование (перенесена фигурная скобка)

### _Task 6_
- тело метода переписано более грамотно: убраны лишние действия;
- логика формирования выходных строк вынесена в отдельный метод; 
- обновлено форматирование (перенесена фигурная скобка)

### _Task 8_
### метод getNames

_- Комментарии (недостатки самой первой версии кода):_ 
1) падает при вызове size() на null-коллекции
2) падает при Person::getFirstName на нулевых персонах
3) падает на вызове remove(0), если в качестве аргумента нам подадут List.of(), т.к. он Immutable
4) remove(0) - лишняя нагрузка по эффективности. Если поступает LinkedList, то будет O(1), но если ArrayList - возникнет O(n). К тому же, мы вынуждены делать дополнительную проверку на пустой список, чего при использовании стримового skip'а не требуется.

_- Изменения:_ 
1) добавлен забытый мной skip(1), необходимый по логике выполнения метода

### метод convertPersonToString
1) Использование String.format() заменено на Collectors.joining(), что обеспечивает более качественную работу, приближенную к тому, что должен был делать исходный код задания

### метод getPersonNames
1) Прошлая версия кода действительно падала, если добавляются одинаковые по ключу объекты. 
В исходном коде задания была проверка на наличие в мапе каждого ключа, я её упустил. 
**Исправляю**, добавляя в коллектор мердж-функцию, которая будет игнорировать все новые значения по дублирующимся ключам.

### метод hasSamePersons

_- Изменения:_ 
1) "Ловля" исключения в прошлой версии действительно была лишняя, т.к. создаёт некорректность работы кода. Поправлено.
2) Одна из коллекций заворачивается в HashSet перед отправкой в disjoint - для улучшения временной эффективности работы метода.

_- Комментарии (за сколько выполняется метод?):_ 
1) Время выполнения зависит от того, какие коллекции пришли. Например, если придёт два ArrayList, то будет O(n^2), потому что disjoint итерируется по одной коллекции (O(n)), и для каждого элемента вызывает contains на другой коллекции (O(n)). Если придёт две HashSet, то сложность станет O(n) за счёт того, что contains для каждого элемента занимает O(1). В принципе, получается, выгоднее нам заранее одну из коллекций преобразовать в HashSet, чтобы disjoint на ней делал contains.

### метод countEven
_- Комментарии (чем плоха изначальная манипуляция?):_ 
1) считаю, в исходном варианте хуже читаемость и лаконичность кода;
2) на параллельном стриме в исходном виде метод отрабатывает некорректно при изменении поля count;
3) производились ненужные действия, создающие ощущения дурного стиля. 
Зачем целому классу нужно поле count, которое локально используется как счётчик в одном методе? 
Зачем даже локально заводить счётчик и изменять его через forEach, если есть понятный и очевидный count() в стриме? Это как итерироваться по какому-нибудь листу, вручную подсчитывая количество элементов, вместо того, чтобы использовать встроенный list.size().

2022-12-28 14:22 UTC, m-kulygin commented on src/main/java/tasks/Task3.java
> +  {
Согласен, поправляю.

2022-12-28 14:23 UTC, m-kulygin commented on src/main/java/tasks/Task3.java
> +            .sorted(Comparator.comparing(Person::getSecondName)
Потому что отсутствовали null-case проверки, а именно:
- если поступающая коллекция == null
- если какой-либо из элементов коллекции == null - упадёт на вызовах методов типа getFirstName ...
- если какие-то поля у конкретной персоны == null - упадёт на сортировке, что поправляется использованием null-friendly компаратора

Правки сделал в новых коммитах, в сводном комментарии также отразил все изменения и ответы на вопросы.

2022-12-28 14:24 UTC, m-kulygin commented on src/main/java/tasks/Task6.java
> +            .flatMap(Set::stream)
Да, согласен, сам видел, что громоздко выходит. Поправил.

2022-12-28 14:24 UTC, m-kulygin commented on src/main/java/tasks/Task8.java
> +  // ИЗМЕНЕНО: метод переписан на стримах с добавлением null-case проверок.
Недостатки самой первой версии кода):
- падает при вызове size() на null-коллекции
- падает при Person::getFirstName на нулевых персонах
- падает на вызове remove(0), если в качестве аргумента нам подадут List.of(), т.к. он Immutable
- remove(0) - лишняя нагрузка по эффективности. Если поступает LinkedList, то будет O(1), но если ArrayList - возникнет O(n). К тому же, мы вынуждены делать дополнительную проверку на пустой список, чего при использовании стримового skip'а не требуется.

2022-12-28 14:25 UTC, m-kulygin commented on src/main/java/tasks/Task8.java
> +                    Optional.ofNullable(person.getMiddleName()).orElse(""));
Да, согласен, поправляю. Правки в новых коммитах, также описал в новом комментарии после коммитов.

2022-12-28 14:26 UTC, m-kulygin commented on src/main/java/tasks/Task8.java
> +            .collect(Collectors.toMap(Person::getId, this::convertPersonToString));
Да, этот код падает, если добавляются одинаковые по ключу объекты.
В исходном коде задания была проверка на наличие в мапе каждого ключа, я её упустил.
Исправляю, добавляя в коллектор мердж-функцию, которая будет игнорировать все новые значения по дублирующимся ключам.

2022-12-28 14:27 UTC, m-kulygin commented on src/main/java/tasks/Task8.java
> +    } catch (Exception e) { System.err.println("EXCEPTION: " + e.getMessage()); }
Да, реально лишний catch, т.к. создаёт некорректность работы кода. Поправлено.

Время выполнения зависит от того, какие коллекции пришли. Например, если придёт два ArrayList, то будет O(n^2), потому что disjoint итерируется по одной коллекции (O(n)), и для каждого элемента вызывает contains на другой коллекции (O(n)). Если придёт две HashSet, то сложность станет O(n) за счёт того, что contains для каждого элемента занимает O(1). В принципе, получается, выгоднее нам заранее одну из коллекций преобразовать в HashSet, чтобы disjoint на ней делал contains.

2022-12-28 14:27 UTC, m-kulygin commented on src/main/java/tasks/Task8.java
> +  public long countEven(Stream<Integer> numbers) // убрано ненужное внутреннее поле count; избыточная манипуляция с этим полем заменена на встроенный метод count
- считаю, в исходном варианте хуже читаемость и лаконичность кода;
- на параллельном стриме в исходном виде метод отрабатывает некорректно при изменении поля count;
- производились ненужные действия, создающие ощущения дурного стиля.
Зачем целому классу нужно поле count, которое локально используется как счётчик в одном методе?
Зачем даже локально заводить счётчик и изменять его через forEach, если есть понятный и очевидный count() в стриме? Это как итерироваться по какому-нибудь листу, вручную подсчитывая количество элементов, вместо того, чтобы использовать встроенный list.size().

2022-12-30 05:11 UTC, genroelgvozo approved these changes

2022-12-30 08:00 UTC, merged